<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/uploads/allimg/150418/1-15041Q24034.jpg ",93,254);
$z[1][4]['ddimg']="/uploads/uploads/allimg/150418/1-15041Q24034.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="200";
$z[1][4]['height']="150";
$z[2]=Array("img"," /uploads/uploads/allimg/150418/1-15041Q24034-50.jpg ",256,424);
$z[2][4]['ddimg']="/uploads/uploads/allimg/150418/1-15041Q24034-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1136";
$z[2][4]['height']="852";
$z[3]=Array("img"," /uploads/uploads/allimg/150418/1-15041Q24034-51.jpg ",426,593);
$z[3][4]['ddimg']="/uploads/uploads/allimg/150418/1-15041Q24034-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="200";
$z[3][4]['height']="150";
$z[4]=Array("img"," /uploads/uploads/allimg/150418/1-15041Q24034-52.jpg ",595,763);
$z[4][4]['ddimg']="/uploads/uploads/allimg/150418/1-15041Q24034-52.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1136";
$z[4][4]['height']="852";
$z[5]=Array("img"," /uploads/uploads/allimg/150418/1-15041Q24034-53.jpg ",765,932);
$z[5][4]['ddimg']="/uploads/uploads/allimg/150418/1-15041Q24034-53.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="354";
$z[5][4]['height']="439";

?>