<?php
$z[0]=Array("global","",52,81);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",426,455);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",580,609);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",734,763);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",1726,1755);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",2259,2288);
$z[5][4]['name']="cfg_templeturl";

?>