<?php
$z[0]=Array("global","",51,80);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",932,961);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",1226,1251);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",1321,1346);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("type","<li class=\"nav-item\">  <a href=\"[field:typeurl/]\">[field:typename/]</a></li> ",1392,1503);
$z[4][4]['typeid']="1";
$z[5]=Array("type","<li class=\"nav-item\">  <a href=\"[field:typeurl/]\">[field:typename/]</a></li> ",1512,1623);
$z[5][4]['typeid']="2";
$z[6]=Array("type","<li class=\"nav-item\">  <a href=\"[field:typeurl/]\">[field:typename/]</a></li> ",1632,1743);
$z[6][4]['typeid']="3";
$z[7]=Array("type","<li class=\"nav-item\">  <a href=\"[field:typeurl/]\">[field:typename/]</a></li> ",1752,1863);
$z[7][4]['typeid']="7";
$z[8]=Array("global","",2086,2115);
$z[8][4]['name']="cfg_templeturl";
$z[9]=Array("global","",2665,2694);
$z[9][4]['name']="cfg_templeturl";
$z[10]=Array("global","",3258,3287);
$z[10][4]['name']="cfg_templeturl";
$z[11]=Array("global","",3779,3808);
$z[11][4]['name']="cfg_templeturl";
$z[12]=Array("global","",4279,4308);
$z[12][4]['name']="cfg_templeturl";

?>