<?php
$z[0]=Array("global","",279,304);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("type","<li>  <a href=\"[field:typeurl/]\">[field:typename/]</a></li> ",378,472);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<li>  <a href=\"[field:typeurl/]\">[field:typename/]</a></li> ",480,574);
$z[2][4]['typeid']="2";
$z[3]=Array("type","<li>  <a href=\"[field:typeurl/]\">[field:typename/]</a></li> ",582,676);
$z[3][4]['typeid']="3";

?>